/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMasterChefOffChainHelper,
  IMasterChefOffChainHelperInterface,
} from "../IMasterChefOffChainHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
    ],
    name: "poolInfo",
    outputs: [
      {
        components: [
          {
            internalType: "contract IBEP20",
            name: "lpToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "allocPoint",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastRewardBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accSpiritPerShare",
            type: "uint256",
          },
          {
            internalType: "uint16",
            name: "depositFeeBP",
            type: "uint16",
          },
        ],
        internalType: "struct IMasterChefOffChainHelper.PoolInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMasterChefOffChainHelper__factory {
  static readonly abi = _abi;
  static createInterface(): IMasterChefOffChainHelperInterface {
    return new utils.Interface(_abi) as IMasterChefOffChainHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMasterChefOffChainHelper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMasterChefOffChainHelper;
  }
}
